# -*- coding: utf-8 -*-
"""Zomato_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k_q6zKUzORe8JBFEwp_3H2K2pFwmMXVG

# **Zomato Data Analysis Project**

**IMPORT LIBRARIES**

---

pandas is use for data manipulation and analysis.




numpy is use for numerical operation.




matplotlib.pyplot & seaborn are use for data visulization
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

"""**Create the data**


"""

# data=pd.read_csv(r"C:\Users\hp\Downloads\Zomato data(1).csv")
data=pd.read_csv(r"/content/Zomato data  (1).csv")

data.head(3)

data.isnull().sum()

data.info()

print(data)

"""**Convert the data type of column-rate**"""

def handalerate(value):
  value=str(value).split("/")
  value=value[0]
  return float(value)
data["rate"]=data["rate"].apply(handalerate)
data.head()

"""**Type of Resturant**"""

sns.countplot(x=data["listed_in(type)"])
plt.xlabel("Type of resturant")
plt.show()

"""***Conclusion*** :- Majority of the resturant falls in dinning category"""

data.head(3)

data_group=data.groupby("listed_in(type)")["votes"].sum()
result=pd.DataFrame({"votes":data_group})

plt.plot(result,marker="o",c="green")
plt.xlabel("Types of Resturant",c="red",size=20)
plt.ylabel("Total Votes",c="red",size=20)
plt.show()

"""**Dinning Resturant has received maximum votes**"""

plt.hist(data["rate"],bins=5)
plt.title("Rating Distribustion")
plt.show()

"""**The Majority restuants received rating from 3.5 to 4**"""

data.head()

cost=data["approx_cost(for two people)"]
sns.countplot(x=cost)
plt.show()

"""**The majority of couple preferr resturants with an approximate cost of 300**"""

data.head(3)

plt.figure(figsize=(8,8))
sns.boxplot(x=data["online_order"],y=data["rate"])

"""**offline order received lower rating in comparison online order**"""

data.head(3)

pivot_table=data.pivot_table(index="listed_in(type)",columns='online_order',aggfunc='size',fill_value=0)
sns.heatmap(pivot_table,annot=True,cmap="YlGnBu",fmt='d')
plt.title("Heatmap")
plt.show()

